name: Deploy
on: 
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: lint
      run: npm run lint
    
    - name: Unit tests
      run: npm run test
    
  build: 
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '16.x'

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    - name: Build app
      run: npm run watch 
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: devops-test-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/devops-test

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    steps: 
    # - name: Dowload artifact
    #   uses: actions/download-artifact@v2
    #   with: 
    #     name: devops-test-${{ github.run_id }}-${{ github.run_number }} 
    #     path: './build'

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.LA_BELLE_PLANTE_KEY }}
      with:
        source: "."
        target: "/var/www/labelleplante"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.LA_BELLE_PLANTE_KEY }}
        run: ls
    
    # - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
    #   with:
    #     heroku_api_key: ${{ secrets.LA_BELLE_PLANTE }}
    #     heroku_app_name: "labelleplantefrontdev"
    #     heroku_email: "gaellecoue@gmail.com"
